name: Helm lint

on:
  push:
    branches:
      - main

jobs:
  lint:
    permissions:
      contents: read
    runs-on: ubuntu-22.04
    container:
      image: dtzar/helm-kubectl:3.11.1
    steps:
      - uses: actions/checkout@v3

      - name: Helm lint
        run: helm lint -f chart/values.yaml chart
