name: Helm release

on:
  push:
    branches:
      - main

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.10.0

      - name: Helm lint
        run: |
          for chart in $(ls charts); do
            args="charts/${chart}"

            if [ -f "charts/${chart}/values.yaml" ]; then
              args="-f charts/${chart}/values.yaml ${args}"
            fi

            helm lint ${args}
          done

      # https://github.com/helm/chart-releaser-action
      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Create gh-pages branch if it doesn't exist
        continue-on-error: true
        run: |
          git checkout -b gh-pages || exit 1
          git rebase main
          git push origin gh-pages

          git checkout main

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.5.0
        with:
          config: "./.github/configs/cr.yaml"
        env:
          CR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
